In [14]:
import sys
sys.path.append('/data/lige/HKN')# Please change accordingly!
import numpy as np
import matplotlib.pyplot as plt
import torch
from os import makedirs
from os.path import join, exists

from manifolds.poincare import PoincareBall
from manifolds.base import ManifoldParameter 
from optim import RiemannianAdam, RiemannianSGD

from kernels.poincare_kernel_points import load_kernels

# Example usage:
manifold = PoincareBall()
radius = 1
num_kpoints = 8
dimension = 64
c=torch.tensor([1.0],dtype=torch.float64,device=torch.device('cpu'))
kernel_tangents = load_kernels(manifold, radius, num_kpoints, dimension, random=False, c=c)
manifold.expmap0(kernel_tangents,c=c)
kernel_points = manifold.expmap0(kernel_tangents,c=c)

In [15]:
for i in range(1,8):
    print(torch.sqrt(manifold.sqdist(kernel_points[0],kernel_points[i],c)))

#for i in range(2,8):
    #print(torch.sqrt(manifold.sqdist(kernel_points[1],kernel_points[i],c)))

for i in range(1,8):
    print(torch.norm(kernel_points[i]))

tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor([1.0000], dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
tensor(0.4621, dtype=torch.float64)
